execute pathogen#infect()

filetype plugin on

if has("syntax")
  syntax on
endif


" Use softtabs
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab
retab


" Simplify window movement
map <c-h> <c-w>h
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l


" Toggle File Explorer
noremap <c-n> :Lex<cr>


" Misc settings
silent! colorscheme desert
set number
set splitright
set ruler


" Use space to recursively toggle folds
" noremap <space> zA


" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd     " Show (partial) command in status line.
set showmatch       " Show matching brackets.
"set ignorecase     " Do case insensitive matching
"set smartcase      " Do smart case matching
"set incsearch      " Incremental search
"set autowrite      " Automatically save before commands like :next and :make
"set hidden     " Hide buffers when they are abandoned
"set mouse=a        " Enable mouse usage (all modes)

" Source a global configuration file if available
" if filereadable("/etc/vim/vimrc.local")
"   source /etc/vim/vimrc.local
" endif


function Repl()
    :vsplit .scratch
    :map <Leader>r <c-w>hgg"qyG<c-w>lggdG:read !q<CR>
endfunction
map <Leader>r :call Repl()<CR>
